### PR TITLE
Danila bladyko hm7 task2

### PR DESCRIPTION
**Pull request by TLittleProgrammer**

### CODE REVIEW

**Review by vladis1350 — DISMISSED** [review]
Lgfm

**Review by javaGuruBY — DISMISSED** [review]
good

**Comment by akupreychik** [comment]
lgfm

**Comment by a-vov4eg** [comment]
I have not idea how it is works, but LGFM

**Review by a-vov4eg — DISMISSED** [review]

**Review by javaGuruBY — APPROVED** [review]
lgfm

**Pull request merged**
