### PR TITLE
Danila hm10 task1

### PR DESCRIPTION
**Pull request by TLittleProgrammer**

### CODE REVIEW

**Comment by Enotik-code** [comment]
lgfm

**Comment by Enotik-code** [comment]
lgfm

**Review by akupreychik — APPROVED** [review]
lgfm

**Review by vladis1350 — APPROVED** [review]
lgfm

**Review by a-vov4eg — APPROVED** [review]
LGFM в целом

**Review by javaGuruBY — APPROVED** [review]
lgfm

**Pull request merged**
