### PR TITLE
Danila bladyko hm8 task2

### PR DESCRIPTION
**Pull request by TLittleProgrammer**

### CODE REVIEW

**Comment by vladis1350** [comment]
lgfm

**Review by vladis1350 — DISMISSED** [review]
lgfm

**Review by javaGuruBY — DISMISSED** [review]
good

**Review by javaGuruBY — CHANGES_REQUESTED** [review]
resolve merge conflict

**Review by vladis1350 — APPROVED** [review]

**Review by javaGuruBY — APPROVED** [review]
lgfm

**Pull request merged**
